
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp awardee.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp details.html $DEPLOYPATH
    - /bin/cp gallery.html $DEPLOYPATH
    - /bin/cp images -R $DEPLOYPATH
    - /bin/cp css -R $DEPLOYPATH